Fix missing using Xunit directive in all test files
Added 'using Xunit;' to resolve FactAttribute compilation errors:
- Services/EPGServiceTests.cs
- Services/RecommendationServiceTests.cs
- Controllers/ContentControllerTests.cs
- Controllers/AuthControllerTests.cs
- Controllers/UserControllerTests.cs
- Controllers/EPGControllerTests.cs
- Controllers/AnalyticsControllerTests.cs
- Controllers/StreamingControllerTests.cs

This fixes the error: 'The type or namespace name FactAttribute could not be found'